version: "3.3"
   
services:
  db:
    image: postgres
    env_file: 
      ./.env
    volumes: 
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file: 
      ./.env
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build: .
    command: celery -A venApi worker -l INFO
    volumes: 
      - .:/usr/src/app
    env_file: 
      ./.env
    depends_on: 
      - api
      - redis
  redis:
    image: "redis:alpine"
volumes: 
  pgdata: