# Generated by Django 3.1.1 on 2020-09-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200926_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
