# Generated by Django 3.1.2 on 2020-10-07 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201007_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_lecturer',
        ),
       
       
    ]
