# Generated by Django 3.1.2 on 2020-10-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201007_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
