# Generated by Django 3.1.1 on 2020-09-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_auto_20200930_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
