# Generated by Django 3.1.2 on 2020-10-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
