# Generated by Django 3.1.2 on 2020-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0006_auto_20201004_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscheduledtimetable',
            name='purpose',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Defence', 'Defence'), ('Meeting', 'Meeting'), ('Test', 'Test')], max_length=7),
        ),
    ]
