# Generated by Django 3.1.2 on 2020-10-06 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Schedule', '0009_auto_20201006_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], max_length=10)),
                ('end_time', models.TimeField()),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='TimetableWithDays',
        ),
        migrations.RemoveField(
            model_name='schooltimetable',
            name='content_type',
        ),
    ]
