# Generated by Django 3.1.2 on 2020-10-07 07:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Schedule', '0009_auto_20201006_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryTimetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], max_length=10, null=True)),
                ('start_date_and_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField()),
                ('venue', models.UUIDField()),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='TimetableWithDays',
        ),
        migrations.RemoveField(
            model_name='schooltimetable',
            name='content_type',
        ),
    ]
