# Generated by Django 3.1.2 on 2020-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0010_auto_20201006_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarytimetable',
            name='start_date_and_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarytimetable',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarytimetable',
            name='day',
            field=models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], max_length=10, null=True),
        ),
    ]
