# Generated by Django 3.1.2 on 2020-10-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0010_auto_20201006_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarytimetable',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
