# Generated by Django 3.1.2 on 2020-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0012_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarytimetable',
            name='start_date_and_time',
        ),
        migrations.AddField(
            model_name='summarytimetable',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
